server:
  port: 10001
spring:
  application:
    name: xxw
#  mail:
#    host: smtp.exmail.qq.com
#    account: info@lingjianbang.com
#    from: info@lingjianbang.com
#    pass: rhCEUQZTHg3xjKdA
#    port: 465
#    protocol: smtp
  mail:
    host: smtp.163.com
    account: catlib@163.com
    from: catlib@163.com
    pass: ljb123qwe
    port: 465
    protocol: smtp
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    enabled: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
      enabled: true
  cache:
    type: REDIS
    cache-names: redis_cache , ehcache
    redis:
      time-to-live: 6000000
  redis:
    database: 0
    host: 212.129.138.41
    port: 6379
    password: xxw2019
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  shutdown-timeout: 100ms
  data:
    mongodb:
      host: anoax.com
      port: 27017
      database: anoax_database
      username: anoax
      password: zhangan@28
      repositories: true
master:
  datasource:
    url: jdbc:mysql://212.129.138.41:3306/www_datlogs_cn_data?characterEncoding=utf-8&zeroDateTimeBehavior=round&useSSL=false
    username: www_datlogs_cn
    password: jKXankiaGNHi3jK2
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    default-executor-type: REUSE
    default-statement-timeout: 25000
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bangxuan.xxw.entity
mapper:
  plugin: tk.mybatis.mapper.generator.MapperPlugin
  Mapper: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
com:
  turbid:
    upload-path:
      images: /
    tencentoss:
      qcloud_file_accesskey: AKIDL7XkZdcxQGxhVFbymTrDXlxbM3f9Pq4D
      qcloud_file_secretkey: QhqaEuQm1JexDJg5MZcu7A2lcQ4b4Phx
      qcloud_file_region: ap-shanghai
      qcloud_file_bucket: web-site-1252739071
security:
  oauth2:
    resource:
      jwt:
        key-value: auth.turbidexplore.com
logging:
  level:
    com.bangxuan.xxw.dao : debug