server:
  port: 10001

spring:
  application:
    name: xxw
  mail:
    host: smtp.exmail.qq.com
    account: info@lingjianbang.com
    from: info@lingjianbang.com
    pass: rhCEUQZTHg3xjKdA
    port: 465
    protocol: smtp
  thymeleaf:
    cache: false #关闭缓存
    prefix: classpath:/templates/ #添加路径前缀
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    enabled: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
      enabled: true
  cache:
    type: REDIS
    cache-names: redis_cache , ehcache #缓存的名字
    redis:
      time-to-live: 6000000  #很重要，缓存的有效时间，以便缓存的过期（单位为毫秒
  redis:
    database: 0
    host: 212.129.138.41
    port: 6379
    password: xxw2019
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  shutdown-timeout: 100ms
  data:
    mongodb:
      host: anoax.com
      port: 27017
      database: anoax_database
      username: anoax
      password: zhangan@28
      repositories: true

master:
  datasource:
    url: jdbc:mysql://212.129.138.41:3306/www_datlogs_cn_data?characterEncoding=utf-8&zeroDateTimeBehavior=round&useSSL=false
    username: www_datlogs_cn
    password: jKXankiaGNHi3jK2
    driverClassName: com.mysql.jdbc.Driver

#cluster:
#  datasource:
#    url: jdbc:mysql://123.206.178.25:3306/yangzi?characterEncoding=utf-8&zeroDateTimeBehavior=round&useSSL=false
#    username: root
#    password: 123uiop!@#$
#    driverClassName: com.mysql.jdbc.Driver


###########################mybatis配置###############################
mybatis:
  configuration:
    #全局映射器启用缓存
    cache-enabled: true
    #查询时,关闭关联对象及时加载以提高性能
    lazy-loading-enabled: false
    #按需加载字段(加载字段由SQL指定),不会加载关联表的所有字段,以提高性能
    aggressive-lazy-loading: false
    #允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    #对于批量更新操作缓存SQL以提高性能
    default-executor-type: REUSE
    #数据库执行超时时间
    default-statement-timeout: 25000
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bangxuan.xxw.entity

# 通用mapper 配置 自动生成dao层代码
mapper:
  plugin: tk.mybatis.mapper.generator.MapperPlugin
  Mapper: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

com:
  turbid:
    upload-path:
      images: /
    sms:
     appid: 1400164813
     appkey: b17bdcc8135762640039ad4d4cedd77b
     smsSign: 浑浊探索
    securitycode: ${random.int[1000,9999]}
    #腾讯云存储服务
    tencentoss:
      qcloud_file_accesskey: AKIDL7XkZdcxQGxhVFbymTrDXlxbM3f9Pq4D
      qcloud_file_secretkey: QhqaEuQm1JexDJg5MZcu7A2lcQ4b4Phx
      #上海存储区
      qcloud_file_region: ap-shanghai
      #正式环境的桶 web-site-1252739071  测试环境 web-test-1252739071
      qcloud_file_bucket: web-site-1252739071

security:
  oauth2:
    resource:
      jwt:
        key-value: auth.turbidexplore.com

# 打印sql
logging:
  level:
    com.bangxuan.xxw.dao : debug